---
title: "Client Report - Can You Predict That?"
subtitle: "Unit 4 Task 1"
author: "Ella Patten"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *
# add the additional libraries you need to import for ML here
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
LetsPlot.setup_html(isolated_frame=True)

```


```{python}
# import your data here using polars and the local dataset file
data_path = 'dwellings_ml.txt'
dwellings = pl.read_csv(data_path)
```

## QUESTION

1. __Take time to get to know your data.__ Based on some initial exploration, identify 3 variables in the dataset you think will have strong predictive ability for determining if a house was built before 1980. Explain/justify the reasoning behind your guesses (for example with plots).

The three variables I think would be helpful is the living area, finished basement, and condition of the house. These don't have a huge correlation, but I think all together they could be helpful.

```{python}
# Optional: code you used to get to know your data

print('Dataset shape:', dwellings.shape)
for c in dwellings.columns:
    print(c)
print(dwellings.select(pl.col("yrbuilt", "stories", "before1980")))

plot_data = dwellings.select(['yrbuilt', 'livearea', 'finbsmnt', 'condition_AVG']).to_pandas()

p1 = (
    ggplot(plot_data, aes(x='yrbuilt', y='livearea'))
    + geom_point(alpha=0.2, size=2)
    + labs( title = 'Year Built vs Living Area', x = 'Year Built', y = 'Living Area')
    + scale_x_continuous(format='{d}')
)

p2 = (
    ggplot(plot_data, aes(x='yrbuilt', y='finbsmnt'))
    + geom_point(alpha=0.2, size=2)
    + labs( title = 'Year Built vs Finished Basement', x = 'Year Built', y = 'Finished Basement')
    + scale_x_continuous(format='{d}')
)

p3 = (
    ggplot(plot_data, aes(x='yrbuilt'))
    + geom_bar()
    + labs( title = 'Count of Houses by Year Built', x = 'Year Built', y = 'Count')
    + scale_x_continuous(format='{d}')
)

plot_grid = gggrid([p1, p2, p3], ncol=1)
plot_grid

```

1. __Build a classification model labeling houses as being built “before 1980” or “during or after 1980”.__ Your goal is to reach or exceed 90% accuracy. Report your final model choice and any other model parameters you may have tweaked (train-test split ratio, tuning parameters, etc).  

Here we're able to use RandomForestClassifier to predict whether a house was built before 1980. I used few features at first and then increased the number of features to see if it would increase the accuracy -- it did, by about 3%. I tweaked the train-test ratio to 70-30 and that seemed to work well, but I didn't do any tuning of the model parameters. I think that could be a next step to try to increase the accuracy even more.

```{python}
# Include and execute your code here
# Don't forget, you need another import statement to import the desired ML model from sklearn
features = dwellings.select(['livearea','finbsmnt','basement','stories','nocars','numbdrm','numbaths','condition_AVG',
    'quality_A','quality_B','quality_C','quality_D','quality_X',
    'gartype_Att','gartype_Det','gartype_None','gartype_CP']).to_numpy()
target = dwellings.select('before1980').to_numpy().ravel()

x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.3, stratify=target)

model = RandomForestClassifier()
model.fit(x_train, y_train)

y_pred = model.predict(x_test)

acc = metrics.accuracy_score(y_test, y_pred)
print('accuracy:', acc)
```

