---
title: "Client Report -How good is it, really?"
subtitle: "Unit 4 Task 2"
author: "Ella Patten"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.ensemble import RandomForestClassifier
from sklearn.inspection import permutation_importance
from sklearn.metrics import confusion_matrix, classification_report
import pandas as pd

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# import your data here using polars and the URL
data = 'dwellings_ml.txt'
dwellings = pl.read_csv(data)
```

## QUESTION 1

1. __Describe the quality of your classification model using 2-3 different evaluation metrics.__ You also need to explain how to define/interpret each of the evaluation metrics you use.  

Here I use 3 different tests to see how accurate and precise my model is. First we use the accuracy score, then I pull in a classification report which is able to read through both the precision, f1-score, and recall of the model.
I also added in a confusion matrix because I thought it was intriguing to see how many of the predictions. The top left block shows us how many were true negatives, the top right shows false negatives, the bottom left shows false positives and the bottom right shows true positives. Here we're able to see how many cases are incorrect.   

```{python}
# Include and execute your code here
# Don't forget, you need another import statement to import the desired ML model from sklearn
feature_names = [
  'livearea','finbsmnt','basement','stories','nocars','numbdrm','numbaths','condition_AVG',
  'quality_A','quality_B','quality_C','quality_D','quality_X',
  'gartype_Att','gartype_Det','gartype_None','gartype_CP'
]
features = dwellings.select(feature_names).to_numpy()
target = dwellings.select('before1980').to_numpy().ravel()
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.3, stratify=target)
model = RandomForestClassifier()
model.fit(x_train, y_train)
y_pred = model.predict(x_test)


acc = metrics.accuracy_score(y_test, y_pred)
print('Accuracy:', acc)

print('Classification report:')
print(classification_report(y_test, y_pred))

print('Confusion matrix:')
cm = confusion_matrix(y_test, y_pred)
print(cm)

```


## QUESTION 2

1. __Justify your classification model by discussing the most important features selected by your model.__ This discussion should include a plot of permutation importance values for the most important features. Were there any features you thought would be importance but weren't?

I ran the permutation test and ploted the top 10 features. In the last task I guessed that the living area, finished basement, and condition of the house would be the most important features. While they were all in the top ten, I thought that the condition of the house would be more important than it was. I was surprised that the number of stories came out as number one. 

```{python}
# Include and execute your code here
r = permutation_importance(model, x_test, y_test, n_repeats=10, random_state=0, n_jobs=1)

importances = pd.Series(r.importances_mean, index=feature_names)
top = importances.nlargest(10)

df_perm = pd.DataFrame({
  'feature': top.index,
  'importance': top.values,
})
df_perm['feature'] = pd.Categorical(df_perm['feature'], categories=df_perm['feature'], ordered=True)

(ggplot(df_perm, aes(x='feature', y='importance', fill='feature'))
 + geom_bar(stat='identity', fill = "blue")
 + labs(
     title='Top 10 Permutation Importances',
     x='Feature',
     y='Mean accuracy decrease'
   )
)
```

## QUESTION 3

1. __For the 3 most important features, explain their relationship to the target variable. Use a plot to illustrate the relationship.__ (3 plots minimum)

Here I grab the top 3 features from the permutation test and plot them against the target variable. The top 3 features were number of stories, number of baths, and number of rooms. We can see that for all three features, the houses built before 1980 tend to have fewer stories, fewer baths, and fewer rooms than those built in 1980 or later.

```{python}
# Include and execute your code here
r = permutation_importance(model, x_test, y_test, n_repeats=10, random_state=0, n_jobs=1)
top_idx = r.importances_mean.argsort()[::-1][:4]
top_features = [feature_names[i] for i in top_idx]

df_q3 = dwellings.select(top_features + ['before1980']).to_pandas()
df_q3['before1980'] = df_q3['before1980'].map({0: '1980 or later', 1: 'before 1980'})
(
    ggplot(df_q3, aes(x='before1980', y=top_features[0], fill='before1980'))
    + geom_boxplot()
    + labs(title=f'Stories by build year group', x='Build year category', y = "Stories", fill='Build year category'))
```
```{python}
(ggplot(df_q3, aes(x='before1980', y=top_features[1], fill='before1980'))
    + geom_boxplot()
    + labs(title=f'Number of baths by build year group', x='Build year category', y="Number of baths", fill='Build year category'))
```
```{python}
(ggplot(df_q3, aes(x='before1980', y=top_features[2], fill='before1980'))
  + geom_boxplot()
  + labs(title=f'Number of rooms by build year group', x='Build year category', y="Number of rooms", fill='Build year category'))
```