---
title: "Client Report - Flights: Column Aggregation"
subtitle: "Unit 2 Task 2"
author: "[STUDENT NAME]"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
from polars import selectors as cs
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))
```


## QUESTION 1

__Calculate the sample size (i.e. number of rows in the dataset) for each airport in each year__. What do you notice?

Here we are finding that for almost every airport has over 10 instances per year sampled. There are some outliers and unknowns but for the most part there is a great sample size from each airport and every year.

```{python}
# Include and execute your code here
new = (
    df
    .group_by('airport_name','year')
    .agg(pl.len().alias("sample size"))
)
print(new.sort("year"))

```

## QUESTION 2

__Which airport has the worst delays?__ Describe the metric you chose, and why you chose it to determine the “worst” airport. Your answer should include a summary table that lists (for each airport) the total number of flights, total number of delayed flights, proportion of delayed flights, and average delay time in hours. 

I decided to sort my table by the percentage of flights which were delayed and then by the amount (in hours) of an average delay. Here we can see which airports delay the highest amount of flights - and the average delay also seems to correlate with the highest percentage of flights. 

```{python}
# Include and execute your code here
worst = (
  df
  .with_columns(pl.selectors.starts_with("num_of").cast(pl.Int64, strict=False)).filter(~pl.any_horizontal(pl.selectors.starts_with("num_of") == -999))
  .group_by("airport_code")
  .agg(pl.col("num_of_delays_total").sum(), pl.col("num_of_flights_total").sum(), pl.col("minutes_delayed_total").sum())
  .with_columns(pct_delayed = pl.col("num_of_delays_total") / pl.col("num_of_flights_total"), avg_delay = (pl.col("minutes_delayed_total")/ 60 / pl.col("num_of_delays_total"))))

print(worst.sort("pct_delayed", "avg_delay", descending= True))
```

## QUESTION 3

__Create a barplot showing the proportion of all flights that are delayed at each airport. Describe what you learn from this graph.__  

Here we see that the San Fransico airport has the highest percentage of delayed flights and the Salt Lake City airport has the least amount of delayed flights. We can also see in this graph that all airports delay less than 30% of their flights. 

```{python}
percent = worst.sort(pl.col("pct_delayed"), descending=True)
# Include and execute your code here
(ggplot(percent, aes(x= "airport_code", y = "pct_delayed"))
 + geom_bar(stat = "identity")
 + labs (title = "Percentage of Flights Delayed vs Airport", x= "Airport (by code)", y = "Percentage of Delayed Flights")
)
```