---
title: "Client Report - Exploring Names"
subtitle: "Unit 1 Task 1"
author: "Ella Patten"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```

```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
df = pl.read_csv("https://posit.byui.edu/content/0d43d66f-d3b7-4c43-8c36-52e3ed69e7f1/names_year_csv.csv")
```

## QUESTION 1

__What was the earliest year that the name ‘Felisha’ was used?__

The earliest year Felisha was used was 1964. It was used 20 times, 9 times in Texas alone. We can find this by filtering the name and sorting by the year. 

```{python}
# Q1
print(df.filter(name = "Felisha").sort('year').head(1))
```


## QUESTION 2

__What year had the most babies named 'David'? How many babies were named 'David' that year?__

This data captures 114 years that the name David was used. It was used with the most frequency in the year 1955, when there were 86,389 people named David.
```{python}
# Q2
print(df.filter(name = "David").sort('Total', descending=True).head(1))

```


## QUESTION 3

__What year did your name hit its peak? How many babies were named your name in that year?__

My name, Ella, hit it's peak in 2010, being used 9,883 times. 

```{python}
# Q3
print(df.filter(name = "Ella").sort("Total", descending=True).head(1))
```


## QUESTION 4

__In the most recent year, what was the most common female name in Utah?__ 

Here we see the most common female name in Utah in the year 2024 is Olivia. Here we are assuming the names Oliver, Liam, Henry, and William are all male names. This assumption leaves us with Olivia, which was used 215 times in the state of Utah in the year 2024. 
```{python}
# Q5
dfq4 = df.select (
  pl.col ('name'),
  pl.col("year"),
  pl.col("UT"),
)
dfq4 = dfq4.sort("year", "UT", descending = True)
print(dfq4.head())
```


---
