---
title: "Client Report - Missing values"
subtitle: "Unit 2 Task 3"
author: "Ella Patten"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
# import all needed libraries
import polars as pl
import requests #new for reading in JSON
import io       #new for reading in JSON
import numpy as np
from lets_plot import *
from polars import selectors as cs
import pyarrow
import pandas as pd

LetsPlot.setup_html(isolated_frame=True)

#load in URL

url = "https://raw.githubusercontent.com/byuidatascience/data4missing/master/data-raw/flights_missing/flights_missing.json"
response = requests.get(url)
df = pl.read_json(io.BytesIO(response.content))

# previous code- filtering out necessary columns and removing outlying data
clean = df.with_columns(pl.selectors.starts_with("num_of").cast(pl.Int64, strict=False)).with_columns(
        pl.selectors.starts_with("num_of").replace(-999, None),
        pl.selectors.starts_with("minutes_").replace(-999, None))


# finding the median and mean for select data columns
median = (clean.select(pl.selectors.starts_with("minutes_delayed"))).median().cast(pl.Float64)

mean = (clean.select(pl.selectors.starts_with("num_of"))).mean().cast(pl.Float64)


# inserting the medians and means into null value
medians = clean.with_columns(    
  [pl.col(c).fill_null(median[c][0]) for c in median.columns] +
  [pl.col(c).fill_null(mean[c][0]) for c in mean.columns])

# edit existing data to find the sum and later the percentage of each required column
medians2 = medians.group_by("airport_code").agg(
  pl.col("num_of_delays_carrier").sum(), 
  pl.col("num_of_delays_security").sum(), 
  pl.col("num_of_delays_late_aircraft").sum(), 
  pl.col("num_of_delays_total").sum()).with_columns(
  pct_delayed_carrier = pl.col("num_of_delays_carrier") / pl.col("num_of_delays_total"), 
  pct_delayed_security = pl.col("num_of_delays_security") / pl.col("num_of_delays_total"), 
  pct_delayed_late = pl.col("num_of_delays_late_aircraft") / pl.col("num_of_delays_total"), 
)

# unpivot table for later use in the graphs
short = medians2.select(["airport_code", "pct_delayed_carrier", "pct_delayed_security", "pct_delayed_late"]).unpivot(
    index="airport_code",
    variable_name="delay_type",
    value_name="pct_delayed"
).with_columns(
    pl.col("delay_type").replace({
        "pct_delayed_carrier": "Carrier",
        "pct_delayed_security": "Security",
        "pct_delayed_late": "Late Aircraft"
    })).sort("airport_code")
```

## Question 1

__Which delay is the worst delay? Keep working with the cleaned dataset you created in the previous task. Compare the proportion of flights delayed due to Carrier, to Security, and to Late Aircraft. Show this comparison in a Chart and a Table. Describe your results__

The highest proportion of delayed flights is becuase of late aircraft. We discover this by finding the sum of the three selected delay types and diving that by the total number of flights delayed, discovering which type of delay is the most frequent. 


```{python}
# create a new data set to present in an organized fashion
summary = short.group_by("delay_type").agg(
    pl.col("pct_delayed").mean()
).sort("pct_delayed", descending=True)

print(summary)

summary_pd = summary.to_pandas()
summary_pd["delay_type"] = pd.Categorical(
    summary_pd["delay_type"],
    categories=summary_pd["delay_type"],
    ordered=True
)

# plot the results in a bar graph
(ggplot(summary_pd, aes(x="delay_type", y="pct_delayed", fill="delay_type"))
 + geom_bar(stat="identity")
 + labs(
     title="Average Proportion of Flights Delayed by Type",
     x="Delay Type",
     y="Average Proportion of Flights Delayed",
     fill="Delay Type"
   )
)
```

## Question 2
__Create another chart that shows the proportion of delays for each reason (Carrier, Security, and Late Aircraft) across all 7 airports. Describe your results__

Here we use the same data from the chart above to examine the proportion of flights delayed by each delay type across airports, sorted alphabetically. Late Aircraft delays are consistently the highest across most airports.

```{python}
# plot the reasons for delays across all 7 airports
(ggplot(short, aes(x="airport_code", y="pct_delayed", color="delay_type", group="delay_type"))
 + geom_line()
 + geom_point()
 + labs(
     title="Proportion of Flights Delayed by Type and Airport",
     x="Airport",
     y="Proportion of Flights Delayed",
     color="Delay Type"
   ))
```