---
title: "Client Report - Baseball Database"
subtitle: "Unit 3 Task 1"
author: "Ella Patten"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code
execute: 
  warning: false
    
---

```{python}
import polars as pl
import numpy as np
import sqlite3
from lets_plot import *

LetsPlot.setup_html(isolated_frame=True)
```


```{python}
# Learn morea about Code Cells: https://quarto.org/docs/reference/cells/cells-jupyter.html

# Include and execute your code here
sqlite_file = 'lahmansbaseballdb.sqlite'
# this file must be in the same location as your .qmd or .py file
con = sqlite3.connect(sqlite_file)
```

```{python}
# Include and execute your code here

# The code below uses some basic SQL code to read in the entire 'batting' table in the database and store it in a polars dataframe called 'results'. You must write polars code to manipulate the results dataframe to address the task.

q = """
    SELECT *
    FROM batting
    """
results = pl.read_database(q, con, infer_schema_length=None) 
# What does infer_schema_length = None do?
results
```

## QUESTION 1

__Use the provided code above to read in the batting table. Then, with Python Polars manipulate the 'results' dataframe to calculate the number of at bats and the batting average for each year a player played. Filter the data frame to only include players with at least 10 at bats that year. Sort the dataframe from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__

Note: A batting average is meant to measure how often a player puts the ball in play and gets to base safely. For this task, use a simplified version of batting average defined as the sum of hits (labeled 'H') divided by number of at bats (labeled 'AB').

Here we can create a new column, using the already established columns for hits and at bats to calculate and save the batting average. Then we filter out the rows in which players had less than 10 at bats and sort the columns by batting average and then their player id. Here we find the highest batting average happened in 1929 with a .51 batting average.

```{python}
# Include and execute your code here
results_per_year = results.with_columns(batting_average = pl.col("H") / pl.col("AB")).filter(pl.col('AB') > 10).sort(["batting_average", 'playerID'], descending = [True, False])

print(results_per_year.select("playerID", 'yearID', "AB", 'H', "batting_average").head(5))
```


## QUESTION 2

__Use the provided code above to read in the batting table. Then, with Python Polars manipulate the 'results' dataframe to calculate the batting average for each player over their entire career (all years combined). Only include players with at least 100 at bats over their entire career. Sort the dataframe from highest batting average to lowest, and then by playerid alphabetically. Show the top 5 results in your report.__ 

Note: A batting average is meant to measure how often a player puts the ball in play and gets to base safely. For this task, use a simplified version of batting average defined as the sum of hits (labeled 'H') divided by number of at bats (labeled 'AB').

For this table I used practically the same methodology. The only thing that changed is I made sure to sum the at bats and hits for each player over all the years and then the table could be filtered by at bats (more than 100) and sorted.

```{python}
# Include and execute your code here
results_total = results.group_by('playerID').agg(pl.col('H').sum().alias('total_hits'), (pl.col('AB').sum().alias("at_bat"))).with_columns(batting_average = pl.col("total_hits") / pl.col("at_bat")).filter(pl.col('at_bat') >= 100).sort(["batting_average", 'playerID'], descending = [True, False])

print(results_total.select("playerID", "at_bat", 'total_hits', "batting_average").head(5))

```


